### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by gnaeus** [gnaeus/AutoMapper.ExtendedConverters#1]
**Features**
- [x] ~~Map fields to properties and vice versa~~

**Common**
- [x] Unit Tests
- [x] Benchmarks
- [x] Documentation & Examples
- [ ] XML Documentation
- [x] ~~Publishing NuGet package~~
- [x] Upgrade to AutoMapper 6
- [x] Work with [Mapster](https://github.com/eswann/Mapster)
